const D={shu:[['廖化',2,'整军'],['王平',1,'固守'],['周仓',2,'忠勇'],['关兴',2,'龙魂'],['张苞',1,'破阵'],['糜芳',2,'运粮'],['严颜',3,'固守'],['马岱',3,'暗袭'],['魏延',2,'奇谋'],['马超',3,'铁骑'],['黄忠',4,'烈弓'],['姜维',3,'麒麟'],['赵云',4,'龙胆护主'],['诸葛亮',0,'八阵推演'],['庞统',1,'连环筹策'],['关羽',3,'青龙偃月斩'],['连弩营',0,'箭雨压制'],['八阵图',0,'阵眼封锁'],['木牛流马',0,'军粮运转'],['昭烈仁德令',0,'仁德疆域']],wei:[['曹洪',2,'援助'],['曹休',3,'疾袭'],['夏侯恩',2,'护剑'],['于禁',2,'坚阵'],['李典',1,'征粮'],['臧霸',3,'镇军'],['毛玠',1,'整军'],['徐晃',3,'断粮'],['张郃',2,'巧变'],['曹仁',2,'铁壁'],['夏侯渊',3,'奔袭'],['乐进',3,'先登'],['许褚',3,'虎痴震岳'],['司马懿',0,'鹰视狼顾'],['甄姬',0,'洛水流华'],['曹操',0,'魏武天命令'],['虎豹骑',0,'铁骑踏营'],['屯田营',0,'积蓄粮草'],['挟天子令',0,'奉诏征伐'],['青州归战旗',0,'号令诸军']]};
const E={整军:'回合开始时强化相邻友军或自身。',固守:'回合开始时强化四方相邻友军。',忠勇:'回合开始时强化最强相邻友军。',龙魂:'回合开始时令相邻友军自动进攻。',破阵:'回合开始时邻敌则永久强化。',运粮:'回合开始时手牌不足则抽牌。',暗袭:'回合开始时削弱随机相邻敌军。',奇谋:'放置时触发相邻友军的回合开始技能。',铁骑:'可进行强化的直线移动。',烈弓:'回合开始时削弱同排随机敌军。',麒麟:'依据双方场上数量强化。',龙胆护主:'回合开始补足战力，并可首次免于被摧毁。',八阵推演:'额外触发其他友军的回合开始技能。',连环筹策:'依据场上数量获取行动或强化。',青龙偃月斩:'强化自身并获得不消耗行动的移动或攻击。',箭雨压制:'回合开始削弱同列或同行其他卡牌。',阵眼封锁:'代替相邻友军被摧毁。',军粮运转:'回合开始额外抽牌或满手强化。',仁德疆域:'下个我方回合起占领相邻空格。',援助:'放置时比较手牌后抽牌。',疾袭:'放置时削弱随机相邻敌军。',护剑:'放置时强化随机相邻友军。',坚阵:'放置时强化所有相邻友军。',征粮:'放置时抽牌。',镇军:'边缘放置时永久强化。',断粮:'放置时随机弃置敌方手牌。',巧变:'放置时随机交换相邻友军位置。',铁壁:'保护相邻友军免于被摧毁。',奔袭:'首次主动移动可直线远行。',先登:'下一张放置卡的放置技能额外结算。',虎痴震岳:'放置时削弱相邻敌军。',鹰视狼顾:'放置、结束回合与战力为零时产生效果。',洛水流华:'本回合可重新放置被摧毁友军。',魏武天命令:'强化友军并阻止我方战力降低。',铁骑踏营:'放置时与随机相邻敌军同毁。',积蓄粮草:'放置时抽至手牌上限。',奉诏征伐:'放置时强化并强制相邻友军攻击。',号令诸军:'放置与移动时影响八方区域战力。'};
let G;const $=s=>document.querySelector(s),rnd=a=>a[Math.floor(Math.random()*a.length)],key=(r,c)=>r+','+c,near=(r,c)=>[[r-1,c],[r+1,c],[r,c-1],[r,c+1]].filter(([a,b])=>a>=0&&a<4&&b>=0&&b<4);
function deck(k,o){return D[k].map((x,i)=>({id:k+i,name:x[0],attack:x[1],power:x[1],skill:x[2],owner:o,row:null,col:null,rest:false,moved:false})).sort(()=>Math.random()-.5)}
function draw(p){if(p.hand.length>=5)return; p.hand.push(p.deck.length?p.deck.pop():{id:crypto.randomUUID(),name:'援兵',attack:1,power:1,skill:'无',owner:p.id})}
function start(){let a=$('#p1').value,b=$('#p2').value,first=Math.random()<.5?1:2;G={turn:1,first,active:first,actions:0,broken:[],board:[],sel:null,log:[],p:{1:{id:1,name:'玩家1',deck:deck(a,1),hand:[]},2:{id:2,name:'玩家2',deck:deck(b,2),hand:[]}}};while(G.broken.length<2){let r=Math.floor(Math.random()*4),c=Math.floor(Math.random()*4);if(!G.broken.some(x=>x.r===r&&x.c===c))G.broken.push({r,c})}for(let i=0;i<(first===1?2:3);i++)draw(G.p[1]);for(let i=0;i<(first===2?2:3);i++)draw(G.p[2]);$('#menu').hidden=true;$('#game').hidden=false;begin()}
function begin(){let p=G.p[G.active];G.board.filter(x=>x.owner===p.id).forEach(x=>{x.rest=false;x.moved=false});draw(p);G.actions=0;log(`${p.name}回合开始，抽取1张卡牌。`);render()}
function log(s){G.log.unshift(`第${G.turn}回合：${s}`)}function at(r,c){return G.board.find(x=>x.row===r&&x.col===c)}function free(r,c){return !G.broken.some(x=>x.r===r&&x.c===c)&&!at(r,c)}
function act(r,c){let p=G.p[G.active],s=G.sel,limit=G.turn===1?1:2;if(!s||G.actions>=limit)return;let card=s.kind==='hand'?p.hand.find(x=>x.id===s.id):G.board.find(x=>x.id===s.id);if(!card)return;if(s.kind==='hand'){if(!free(r,c))return;p.hand=p.hand.filter(x=>x!==card);Object.assign(card,{row:r,col:c,rest:true});G.board.push(card);log(`${card.name}放置于${r+1}-${c+1}，进入休整。`)}else{if(card.rest||card.moved||!near(card.row,card.col).some(x=>x[0]===r&&x[1]===c))return;let d=at(r,c);if(d&&d.owner===card.owner)return;card.moved=true;if(!d){card.row=r;card.col=c;log(`${card.name}移动至${r+1}-${c+1}。`)}else if(card.power>d.power){G.board=G.board.filter(x=>x!==d);card.row=r;card.col=c;log(`${card.name}击破${d.name}并进入目标格。`)}else if(card.power<d.power){G.board=G.board.filter(x=>x!==card);log(`${card.name}攻击失败，被${d.name}摧毁。`)}else{G.board=G.board.filter(x=>x!==card&&x!==d);log(`${card.name}与${d.name}同归于尽。`)}}G.actions++;G.sel=null;check();render()}
function check(){let n={1:0,2:0};G.board.forEach(x=>n[x.owner]++);if(n[1]>=8||n[2]>=8){alert(`${n[1]>=8?'玩家1':'玩家2'}占领8格，获胜！`);location.reload()}}
function end(){if(G.turn>=30){alert('30回合结束');location.reload();return}G.turn++;G.active=G.active===1?2:1;begin()}
function render(){let p=G.p[G.active];$('#turn').textContent=`第${G.turn}/30回合 · ${p.name}`;$('#actions').textContent=`行动 ${G.actions}/${G.turn===1?1:2}`;$('#notice').textContent=G.sel?'请选择目标格。':'选择手牌放置，或选择己方非休整卡牌移动。';$('#board').innerHTML='';for(let r=0;r<4;r++)for(let c=0;c<4;c++){let el=document.createElement('button');el.className='cell'+(G.broken.some(x=>x.r===r&&x.c===c)?' broken':'');let x=at(r,c);el.onclick=()=>act(r,c);if(x)el.innerHTML=`<div class="unit p${x.owner}"><b>${x.name}</b><span class="power">${x.power}</span><small class="skill">${x.skill}</small></div>`;else el.textContent=el.classList.contains('broken')?'破坏格':`${r+1}-${c+1}`;$('#board').append(el)}$('#handTitle').textContent=`${p.name}的手牌`;$('#hand').innerHTML='';p.hand.forEach(x=>{let b=document.createElement('button');b.className='card'+(G.sel?.id===x.id?' selected':'');b.innerHTML=`<h3>${x.name} <b>${x.power}</b></h3><small>${x.skill}</small><p class="effect">${E[x.skill]||'无技能。'}</p>`;b.onclick=()=>{G.sel={kind:'hand',id:x.id};render()};$('#hand').append(b)});for(let id of [1,2])$('#'+(id===1?'left':'right')).innerHTML=`<div class="panel"><h2>${G.p[id].name}</h2><p>占领：${G.board.filter(x=>x.owner===id).length}/8</p><p>手牌：${G.p[id].hand.length}/5</p><p>牌库：${G.p[id].deck.length}</p></div>`;$('#log').innerHTML=G.log.map(x=>`<li>${x}</li>`).join('')}
$('#start').onclick=start;$('#end').onclick=end;$('#catalog').innerHTML=['shu','wei'].map(k=>D[k].map(x=>`<article class="catalog-card"><b>三国·${k==='shu'?'蜀':'魏'} ${x[0]}</b> · 战力${x[1]}<small>${x[2]}：${E[x[2]]}</small></article>`).join('')).join('');
