'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const assert = require('node:assert/strict');
const P = require('./presets.js');
const W = require('./web-effects.js');
const { build, render } = require('./build-presets.cjs');
const { engine, regression } = require('./verify.cjs');
assert.equal(fs.readFileSync(path.join(__dirname, 'presets.js'), 'utf8'), render(build()), 'Regenerate stale presets first');
const baseline = engine(), original = regression(baseline), maintained = regression(engine(W.exportScript(P.cards)));
assert.deepEqual(maintained, original, 'Maintained effects differ from the production regression results');
assert.ok(maintained.every(g => g.failed === 0));
const covered = new Set(maintained[1].results.map(r => r.id)); assert.equal(covered.size, 90);
const total = maintained.reduce((n, g) => n + g.passed, 0);
const cell = text => String(text).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const rows = P.cards.map(entry => {
  const runtime = baseline.CARD_EFFECTS_V2[entry.source.module.split('-')[0]][entry.source.id];
  const hooks = Object.keys(runtime).filter(k => typeof runtime[k] === 'function');
  const flags = Object.keys(runtime.flags || {});
  const digest = crypto.createHash('sha256').update(JSON.stringify(Object.fromEntries(Object.entries(runtime).map(([k, v]) => [k, typeof v === 'function' ? v.toString() : v])))).digest('hex').slice(0, 12);
  assert.ok(covered.has(entry.source.id));
  return `| ${[entry.source.id, entry.card.name, entry.card.camp, entry.web ? 'Web 实际脚本' : 'Unity 效果节点', hooks.join(', ') || '无事件', flags.join(', ') || '无', Object.keys(entry.web?.helpers || {}).join(', ') || '无', digest, '通过'].map(cell).join(' | ')} |`;
});
const notes = P.cards.filter(e => e.source.note).map(e => `- **${e.source.id} ${e.card.name}**：${e.source.note}`);
const report = `# 卡牌工坊逐卡核对记录\n\n由 \`node card-workshop/audit.cjs\` 生成；不要手工修改。\n\n预存版本：\`${P.version}\`。正式 90 张卡全部覆盖：13 张保持现有 Unity 节点编辑，77 张原参考卡已接入 Web 实际技能维护。\n\n已在未修改的正式规则引擎中加载导出技能包，${total} 项回归断言通过；卡牌边界断言覆盖全部 90 个原始 ID。源函数体、事件列表、被动标记及运行时常量另由 web-effects.test.cjs 对 77 张逐项精确比对。辅助函数随卡牌闭包保存，避免丢失目标选择与连锁规则。\n\n这些是现有规则的回归检查，不穷举未来所有自定义技能组合。UI 中脚本编辑后的回归差异需要按设计意图复核。流程图为说明，实际 Web 效果由脚本和被动标记执行；Unity 格式不承载 Web 脚本。\n\n| 原卡 ID | 卡名 | 势力 | 维护方式 | 实际事件 | 被动标记 | 辅助函数 | 原实现摘要 SHA256 | 边界检查 |\n|---|---|---|---|---|---|---|---|---|\n${rows.join('\n')}\n\n## 已记录的规则差异与边界\n\n以当前正式代码为基准，保留以下已存在的差异，未擅自改写原游戏规则。甄姬缺失的减益保护标记可在工坊显式维护。\n\n${notes.join('\n')}\n`;
const output = path.join(__dirname, 'CARD_EFFECT_AUDIT.md');
if (process.argv.includes('--check')) assert.equal(fs.readFileSync(output, 'utf8'), report, 'Audit report is stale');
else fs.writeFileSync(output, report, 'utf8');
console.log(`Audited 90 cards / 77 maintained Web implementations / ${total} passing assertions.`);
